from models_enums import CuisineType, EstablishmentType, MealType, DiningStyle, PopularFoodItem, DietaryPreference

# 1. מילון תמונות מלא - כיסוי של 100% מהאופציות המשפיעות על הוויזואליות
IMAGE_MAPPING = {
    # Popular Food Items (עדיפות 1)
    "PopularFoodItem.HAMBURGER": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    "PopularFoodItem.SUSHI": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500",
    "PopularFoodItem.PIZZA_PASTA": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
    "PopularFoodItem.ICE_CREAM_DESSERT": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500",
    "PopularFoodItem.NOODLES_RAMEN": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500",
    "PopularFoodItem.SEAFOOD": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500",
    "PopularFoodItem.CHICKEN": "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=500",
    "PopularFoodItem.STEAK_BBQ": "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    
    # Cuisine Types (עדיפות 2 - כיסוי מלא של כל המטבחים)
    "CuisineType.AMERICAN": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    "CuisineType.ITALIAN": "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=500",
    "CuisineType.CHINESE": "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=500",
    "CuisineType.JAPANESE": "https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=500",
    "CuisineType.MEXICAN_LATIN": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500",
    "CuisineType.ASIAN_FUSION": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    "CuisineType.INDIAN": "https://images.unsplash.com/photo-1585938338392-50a59970d2ee?w=500",
    "CuisineType.MEDITERRANEAN_MIDDLE_EAST": "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=500",
    "CuisineType.EUROPEAN": "https://images.unsplash.com/photo-1595855759920-86582396756a?w=500",
    
    # Establishment Types (עדיפות 3 - ברירות מחדל קבועות)
    "EstablishmentType.RESTAURANT": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500",
    "EstablishmentType.BAR_PUB": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=500",
    "EstablishmentType.CAFE": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
    "EstablishmentType.BAKERY_CONFECTIONERY": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500"
}

# 2. מילון המיפוי הגדול מה-Parquet
RAW_CATEGORY_MAPPING = {
    "American restaurant": [CuisineType.AMERICAN],
    "Traditional American restaurant": [CuisineType.AMERICAN],
    "Southern restaurant (US)": [CuisineType.AMERICAN],
    "Southwestern restaurant (US)": [CuisineType.AMERICAN],
    "Cajun restaurant": [CuisineType.AMERICAN],
    "Creole restaurant": [CuisineType.AMERICAN],
    "Contemporary Louisiana restaurant": [CuisineType.AMERICAN],
    "Canadian restaurant": [CuisineType.AMERICAN],
    "Italian restaurant": [CuisineType.ITALIAN],
    "Northern Italian restaurant": [CuisineType.ITALIAN],
    "Southern Italian restaurant": [CuisineType.ITALIAN],
    "Sicilian restaurant": [CuisineType.ITALIAN],
    "Roman restaurant": [CuisineType.ITALIAN],
    "Pizza": [CuisineType.ITALIAN, PopularFoodItem.PIZZA_PASTA],
    "Pizza restaurant": [CuisineType.ITALIAN, EstablishmentType.RESTAURANT, PopularFoodItem.PIZZA_PASTA],
    "Pizza Takeout": [CuisineType.ITALIAN, DiningStyle.FAST_FOOD, PopularFoodItem.PIZZA_PASTA],
    "Pizza takeaway": [CuisineType.ITALIAN, DiningStyle.FAST_FOOD, PopularFoodItem.PIZZA_PASTA],
    "Pizza delivery": [CuisineType.ITALIAN, DiningStyle.FAST_FOOD, PopularFoodItem.PIZZA_PASTA],
    "Pasta shop": [CuisineType.ITALIAN, PopularFoodItem.PIZZA_PASTA],
    "Chinese restaurant": [CuisineType.CHINESE, EstablishmentType.RESTAURANT],
    "Chinese food": [CuisineType.CHINESE],
    "Delivery Chinese restaurant": [CuisineType.CHINESE, DiningStyle.FAST_FOOD],
    "Chinese takeaway": [CuisineType.CHINESE, DiningStyle.FAST_FOOD],
    "Dim sum restaurant": [CuisineType.CHINESE, EstablishmentType.RESTAURANT],
    "Cantonese restaurant": [CuisineType.CHINESE],
    "Hunan restaurant": [CuisineType.CHINESE],
    "Sichuan restaurant": [CuisineType.CHINESE],
    "Shanghainese restaurant": [CuisineType.CHINESE],
    "Mandarin restaurant": [CuisineType.CHINESE],
    "Hong Kong style fast food restaurant": [CuisineType.CHINESE, DiningStyle.FAST_FOOD],
    "Chinese noodle restaurant": [CuisineType.CHINESE, PopularFoodItem.NOODLES_RAMEN],
    "Japanese restaurant": [CuisineType.JAPANESE, EstablishmentType.RESTAURANT],
    "Authentic Japanese restaurant": [CuisineType.JAPANESE, EstablishmentType.RESTAURANT],
    "Japanese food": [CuisineType.JAPANESE],
    "Sushi restaurant": [CuisineType.JAPANESE, EstablishmentType.RESTAURANT, PopularFoodItem.SUSHI],
    "Sushi takeaway": [CuisineType.JAPANESE, DiningStyle.FAST_FOOD, PopularFoodItem.SUSHI],
    "Conveyor belt sushi restaurant": [CuisineType.JAPANESE, EstablishmentType.RESTAURANT, PopularFoodItem.SUSHI],
    "Izakaya restaurant": [CuisineType.JAPANESE, EstablishmentType.BAR_PUB],
    "Modern izakaya restaurants": [CuisineType.JAPANESE, EstablishmentType.BAR_PUB],
    "Kaiseki restaurant": [CuisineType.JAPANESE, DiningStyle.GOURMET],
    "Teppanyaki restaurant": [CuisineType.JAPANESE, EstablishmentType.RESTAURANT],
    "Tempura restaurant": [CuisineType.JAPANESE],
    "Ramen restaurant": [CuisineType.JAPANESE, PopularFoodItem.NOODLES_RAMEN],
    "Udon noodle restaurant": [CuisineType.JAPANESE, PopularFoodItem.NOODLES_RAMEN],
    "Soba noodle shop": [CuisineType.JAPANESE, PopularFoodItem.NOODLES_RAMEN],
    "Katsudon restaurant": [CuisineType.JAPANESE],
    "Sukiyaki restaurant": [CuisineType.JAPANESE],
    "Sukiyaki and Shabu Shabu restaurant": [CuisineType.JAPANESE],
    "Shabu-shabu restaurant": [CuisineType.JAPANESE],
    "Tonkatsu restaurant": [CuisineType.JAPANESE],
    "Yakitori restaurant": [CuisineType.JAPANESE, PopularFoodItem.STEAK_BBQ],
    "Yakiniku restaurant": [CuisineType.JAPANESE, PopularFoodItem.STEAK_BBQ],
    "Yakisoba Restaurant": [CuisineType.JAPANESE, PopularFoodItem.NOODLES_RAMEN],
    "Takoyaki restaurant": [CuisineType.JAPANESE],
    "Anago restaurant": [CuisineType.JAPANESE],
    "Angler fish restaurant": [CuisineType.JAPANESE, PopularFoodItem.SEAFOOD],
    "Seafood donburi restaurant": [CuisineType.JAPANESE, PopularFoodItem.SEAFOOD, PopularFoodItem.SUSHI],
    "Mexican restaurant": [CuisineType.MEXICAN_LATIN, EstablishmentType.RESTAURANT],
    "Mexican food": [CuisineType.MEXICAN_LATIN],
    "Mexican goods store": [CuisineType.MEXICAN_LATIN],
    "Mexican grocery store": [CuisineType.MEXICAN_LATIN],
    "Mexican torta restaurant": [CuisineType.MEXICAN_LATIN],
    "Taco restaurant": [CuisineType.MEXICAN_LATIN, DiningStyle.FAST_FOOD],
    "Tex-Mex restaurant": [CuisineType.MEXICAN_LATIN],
    "Burrito restaurant": [CuisineType.MEXICAN_LATIN, DiningStyle.FAST_FOOD],
    "Tamale shop": [CuisineType.MEXICAN_LATIN, DiningStyle.FAST_FOOD],
    "Tortilla shop": [CuisineType.MEXICAN_LATIN],
    "Pozole restaurant": [CuisineType.MEXICAN_LATIN],
    "Oaxacan restaurant": [CuisineType.MEXICAN_LATIN],
    "Yucatan restaurant": [CuisineType.MEXICAN_LATIN],
    "Spanish restaurant": [CuisineType.MEXICAN_LATIN],
    "Tapas restaurant": [CuisineType.MEXICAN_LATIN],
    "Tapas bar": [CuisineType.MEXICAN_LATIN, EstablishmentType.BAR_PUB],
    "Latin American restaurant": [CuisineType.MEXICAN_LATIN],
    "South American restaurant": [CuisineType.MEXICAN_LATIN],
    "Central American restaurant": [CuisineType.MEXICAN_LATIN],
    "Brazilian restaurant": [CuisineType.MEXICAN_LATIN],
    "Argentinian restaurant": [CuisineType.MEXICAN_LATIN],
    "Peruvian restaurant": [CuisineType.MEXICAN_LATIN],
    "Colombian restaurant": [CuisineType.MEXICAN_LATIN],
    "Venezuelan restaurant": [CuisineType.MEXICAN_LATIN],
    "Salvadoran restaurant": [CuisineType.MEXICAN_LATIN],
    "Cuban restaurant": [CuisineType.MEXICAN_LATIN],
    "Dominican restaurant": [CuisineType.MEXICAN_LATIN],
    "Puerto Rican restaurant": [CuisineType.MEXICAN_LATIN],
    "Guatemalan restaurant": [CuisineType.MEXICAN_LATIN],
    "Honduran restaurant": [CuisineType.MEXICAN_LATIN],
    "Nicaraguan restaurant": [CuisineType.MEXICAN_LATIN],
    "Pan-Latin restaurant": [CuisineType.MEXICAN_LATIN],
    "Nuevo Latino restaurant": [CuisineType.MEXICAN_LATIN],
    "Basque restaurant": [CuisineType.MEXICAN_LATIN],
    "Asian restaurant": [CuisineType.ASIAN_FUSION],
    "Asian fusion restaurant": [CuisineType.ASIAN_FUSION],
    "Pan-Asian restaurant": [CuisineType.ASIAN_FUSION],
    "Southeast Asian restaurant": [CuisineType.ASIAN_FUSION],
    "South Asian restaurant": [CuisineType.ASIAN_FUSION],
    "Thai restaurant": [CuisineType.ASIAN_FUSION],
    "Vietnamese restaurant": [CuisineType.ASIAN_FUSION],
    "Pho restaurant": [CuisineType.ASIAN_FUSION, PopularFoodItem.NOODLES_RAMEN],
    "Korean restaurant": [CuisineType.ASIAN_FUSION],
    "Korean barbecue restaurant": [CuisineType.ASIAN_FUSION, PopularFoodItem.STEAK_BBQ],
    "Korean beef restaurant": [CuisineType.ASIAN_FUSION, PopularFoodItem.STEAK_BBQ],
    "Korean rib restaurant": [CuisineType.ASIAN_FUSION, PopularFoodItem.STEAK_BBQ],
    "Soondae restaurant": [CuisineType.ASIAN_FUSION],
    "Taiwanese restaurant": [CuisineType.ASIAN_FUSION],
    "Malaysian restaurant": [CuisineType.ASIAN_FUSION],
    "Singaporean restaurant": [CuisineType.ASIAN_FUSION],
    "Indonesian restaurant": [CuisineType.ASIAN_FUSION],
    "Cambodian restaurant": [CuisineType.ASIAN_FUSION],
    "Laotian restaurant": [CuisineType.ASIAN_FUSION],
    "Burmese restaurant": [CuisineType.ASIAN_FUSION],
    "Nepalese restaurant": [CuisineType.ASIAN_FUSION],
    "Tibetan restaurant": [CuisineType.ASIAN_FUSION],
    "Afghani restaurant": [CuisineType.ASIAN_FUSION],
    "Pakistani restaurant": [CuisineType.ASIAN_FUSION],
    "Bangladeshi restaurant": [CuisineType.ASIAN_FUSION],
    "Indian restaurant": [CuisineType.INDIAN, EstablishmentType.RESTAURANT],
    "Modern Indian restaurant": [CuisineType.INDIAN, DiningStyle.GOURMET],
    "South Indian restaurant": [CuisineType.INDIAN],
    "Punjabi restaurant": [CuisineType.INDIAN],
    "Biryani restaurant": [CuisineType.INDIAN],
    "Indian Muslim restaurant": [CuisineType.INDIAN, DietaryPreference.HALAL],
    "Indian sizzler restaurant": [CuisineType.INDIAN],
    "Indian takeaway": [CuisineType.INDIAN, DiningStyle.FAST_FOOD],
    "Mediterranean restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, EstablishmentType.RESTAURANT],
    "Middle Eastern restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Israeli restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Falafel restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, DiningStyle.FAST_FOOD],
    "Kebab shop": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, DiningStyle.FAST_FOOD],
    "Halal restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, DietaryPreference.HALAL],
    "Kosher restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, DietaryPreference.KOSHER],
    "Greek restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Gyro restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST, DiningStyle.FAST_FOOD],
    "Lebanese restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Syrian restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Turkish restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Yemenite restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Armenian restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Persian restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Egyptian restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Moroccan restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "Tunisian restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "North African restaurant": [CuisineType.MEDITERRANEAN_MIDDLE_EAST],
    "European restaurant": [CuisineType.EUROPEAN],
    "Continental restaurant": [CuisineType.EUROPEAN],
    "Modern European restaurant": [CuisineType.EUROPEAN, DiningStyle.GOURMET],
    "Western restaurant": [CuisineType.EUROPEAN],
    "Brasserie": [CuisineType.EUROPEAN, EstablishmentType.RESTAURANT],
    "Bistro": [CuisineType.EUROPEAN, EstablishmentType.RESTAURANT],
    "Provence restaurant": [CuisineType.EUROPEAN],
    "Southwest France restaurant": [CuisineType.EUROPEAN],
    "Alsace restaurant": [CuisineType.EUROPEAN],
    "Belgian restaurant": [CuisineType.EUROPEAN],
    "Swiss restaurant": [CuisineType.EUROPEAN],
    "Austrian restaurant": [CuisineType.EUROPEAN],
    "German restaurant": [CuisineType.EUROPEAN],
    "British restaurant": [CuisineType.EUROPEAN],
    "Modern British restaurant": [CuisineType.EUROPEAN, DiningStyle.GOURMET],
    "English restaurant": [CuisineType.EUROPEAN],
    "Irish restaurant": [CuisineType.EUROPEAN],
    "Irish pub": [CuisineType.EUROPEAN, EstablishmentType.BAR_PUB],
    "Portuguese restaurant": [CuisineType.EUROPEAN],
    "Romanian restaurant": [CuisineType.EUROPEAN],
    "Czech restaurant": [CuisineType.EUROPEAN],
    "Hungarian restaurant": [CuisineType.EUROPEAN],
    "Polish restaurant": [CuisineType.EUROPEAN],
    "Ukrainian restaurant": [CuisineType.EUROPEAN],
    "Russian restaurant": [CuisineType.EUROPEAN],
    "Uzbeki restaurant": [CuisineType.EUROPEAN],
    "Georgian restaurant": [CuisineType.EUROPEAN],
    "Croatian restaurant": [CuisineType.EUROPEAN],
    "Serbian restaurant": [CuisineType.EUROPEAN],
    "Scandinavian restaurant": [CuisineType.EUROPEAN],
    "Swedish restaurant": [CuisineType.EUROPEAN],
    "Danish restaurant": [CuisineType.EUROPEAN],
    "French restaurant": [CuisineType.EUROPEAN],
    "Haute French restaurant": [CuisineType.EUROPEAN, DiningStyle.GOURMET],
    "Modern French restaurant": [CuisineType.EUROPEAN, DiningStyle.GOURMET],
    "Restaurant": [EstablishmentType.RESTAURANT],
    "Restaurant or cafe": [EstablishmentType.RESTAURANT, EstablishmentType.CAFE],
    "Buffet restaurant": [EstablishmentType.RESTAURANT, MealType.LUNCH],
    "Family restaurant": [EstablishmentType.RESTAURANT],
    "Cafeteria": [EstablishmentType.RESTAURANT, MealType.LUNCH],
    "Diner": [EstablishmentType.RESTAURANT, MealType.BREAKFAST_BRUNCH],
    "Traditional restaurant": [EstablishmentType.RESTAURANT],
    "Eclectic restaurant": [EstablishmentType.RESTAURANT],
    "Dinner theater": [EstablishmentType.RESTAURANT, MealType.DINNER],
    "Meat dish restaurant": [EstablishmentType.RESTAURANT],
    "Down home cooking restaurant": [EstablishmentType.RESTAURANT],
    "Country food restaurant": [EstablishmentType.RESTAURANT],
    "Bar": [EstablishmentType.BAR_PUB],
    "Pub": [EstablishmentType.BAR_PUB],
    "Bar & grill": [EstablishmentType.BAR_PUB, PopularFoodItem.STEAK_BBQ],
    "Gastropub": [EstablishmentType.BAR_PUB, DiningStyle.GOURMET],
    "Beer garden": [EstablishmentType.BAR_PUB],
    "Beer hall": [EstablishmentType.BAR_PUB],
    "Brewpub": [EstablishmentType.BAR_PUB],
    "Brewery": [EstablishmentType.BAR_PUB],
    "Cider bar": [EstablishmentType.BAR_PUB],
    "Wine bar": [EstablishmentType.BAR_PUB],
    "Tiki bar": [EstablishmentType.BAR_PUB],
    "Salsa bar": [EstablishmentType.BAR_PUB],
    "Cocktail bar": [EstablishmentType.BAR_PUB],
    "Hookah bar": [EstablishmentType.BAR_PUB],
    "Piano bar": [EstablishmentType.BAR_PUB],
    "Dart bar": [EstablishmentType.BAR_PUB],
    "Sports bar": [EstablishmentType.BAR_PUB],
    "Lounge": [EstablishmentType.BAR_PUB],
    "Stand bar": [EstablishmentType.BAR_PUB],
    "Wine cellar": [EstablishmentType.BAR_PUB],
    "Wine club": [EstablishmentType.BAR_PUB],
    "Winery": [EstablishmentType.BAR_PUB],
    "Sake brewery": [EstablishmentType.BAR_PUB],
    "Club": [EstablishmentType.BAR_PUB],
    "Dance club": [EstablishmentType.BAR_PUB],
    "Disco club": [EstablishmentType.BAR_PUB],
    "Night club": [EstablishmentType.BAR_PUB],
    "Live music bar": [EstablishmentType.BAR_PUB],
    "Blues club": [EstablishmentType.BAR_PUB],
    "Comedy club": [EstablishmentType.BAR_PUB],
    "Bakery": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Chinese bakery": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Wholesale bakery": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Wedding bakery": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Pastry shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Patisserie": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Cake shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Cookie shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Cupcake shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Pie shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Donut shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Pretzel store": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Steamed bun shop": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Chocolate shop": [EstablishmentType.BAKERY_CONFECTIONERY, PopularFoodItem.ICE_CREAM_DESSERT],
    "Chocolate cafe": [EstablishmentType.BAKERY_CONFECTIONERY, EstablishmentType.CAFE],
    "Chocolate artisan": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Confectionery": [EstablishmentType.BAKERY_CONFECTIONERY],
    "Cafe": [EstablishmentType.CAFE],
    "Coffee shop": [EstablishmentType.CAFE],
    "Coffee stand": [EstablishmentType.CAFE],
    "Coffee store": [EstablishmentType.CAFE],
    "Espresso bar": [EstablishmentType.CAFE],
    "Coffee": [EstablishmentType.CAFE],
    "Coffee roasters": [EstablishmentType.CAFE],
    "Tea house": [EstablishmentType.CAFE],
    "Chinese tea house": [EstablishmentType.CAFE],
    "Bubble tea store": [EstablishmentType.CAFE],
    "Internet cafe": [EstablishmentType.CAFE],
    "Art cafe": [EstablishmentType.CAFE],
    "Childrens cafe": [EstablishmentType.CAFE],
    "Breakfast restaurant": [MealType.BREAKFAST_BRUNCH, EstablishmentType.RESTAURANT],
    "Brunch restaurant": [MealType.BREAKFAST_BRUNCH, EstablishmentType.RESTAURANT],
    "Pancake restaurant": [MealType.BREAKFAST_BRUNCH],
    "Lunch restaurant": [MealType.LUNCH, EstablishmentType.RESTAURANT],
    "Box lunch supplier": [MealType.LUNCH],
    "Dinner": [MealType.DINNER],
    "Fine dining restaurant": [DiningStyle.GOURMET, EstablishmentType.RESTAURANT],
    "Gourmet grocery store": [DiningStyle.GOURMET],
    "Fast food restaurant": [DiningStyle.FAST_FOOD, EstablishmentType.RESTAURANT],
    "Takeout Restaurant": [DiningStyle.FAST_FOOD],
    "Takeout restaurant": [DiningStyle.FAST_FOOD],
    "Delivery Restaurant": [DiningStyle.FAST_FOOD],
    "Sandwich shop": [DiningStyle.FAST_FOOD, EstablishmentType.RESTAURANT],
    "Deli": [DiningStyle.FAST_FOOD],
    "Japanese delicatessen": [DiningStyle.FAST_FOOD, CuisineType.JAPANESE],
    "Salad shop": [DiningStyle.FAST_FOOD],
    "Snack bar": [DiningStyle.FAST_FOOD],
    "Soup shop": [DiningStyle.FAST_FOOD],
    "Soup restaurant": [DiningStyle.FAST_FOOD, EstablishmentType.RESTAURANT],
    "Porridge restaurant": [DiningStyle.FAST_FOOD],
    "Quick bite": [DiningStyle.FAST_FOOD],
    "Food court": [DiningStyle.FAST_FOOD, MealType.LUNCH],
    "Hamburger restaurant": [PopularFoodItem.HAMBURGER, DiningStyle.FAST_FOOD],
    "Grill": [PopularFoodItem.HAMBURGER, PopularFoodItem.STEAK_BBQ],
    "Ice cream shop": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Frozen yogurt shop": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Fruit parlor": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Açaí shop": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Sweets and dessert buffet": [PopularFoodItem.ICE_CREAM_DESSERT, MealType.DINNER],
    "Dessert restaurant": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Dessert shop": [PopularFoodItem.ICE_CREAM_DESSERT],
    "Seafood": [PopularFoodItem.SEAFOOD],
    "Seafood restaurant": [PopularFoodItem.SEAFOOD, EstablishmentType.RESTAURANT],
    "Fish and seafood restaurant": [PopularFoodItem.SEAFOOD, EstablishmentType.RESTAURANT],
    "Oyster bar restaurant": [PopularFoodItem.SEAFOOD, EstablishmentType.BAR_PUB],
    "Crab house": [PopularFoodItem.SEAFOOD, PopularFoodItem.STEAK_BBQ],
    "Fish & chips restaurant": [PopularFoodItem.SEAFOOD, DiningStyle.FAST_FOOD],
    "Fish and chips takeaway": [PopularFoodItem.SEAFOOD, DiningStyle.FAST_FOOD],
    "Chicken restaurant": [PopularFoodItem.CHICKEN],
    "Chicken shop": [PopularFoodItem.CHICKEN, DiningStyle.FAST_FOOD],
    "Chicken wings restaurant": [PopularFoodItem.CHICKEN, EstablishmentType.BAR_PUB],
    "Fried chicken takeaway": [PopularFoodItem.CHICKEN, DiningStyle.FAST_FOOD],
    "Steak house": [PopularFoodItem.STEAK_BBQ, EstablishmentType.RESTAURANT],
    "Chophouse restaurant": [PopularFoodItem.STEAK_BBQ, DiningStyle.GOURMET],
    "Barbecue restaurant": [PopularFoodItem.STEAK_BBQ],
    "Vegan restaurant": [DietaryPreference.VEGAN, DietaryPreference.VEGETARIAN],
    "Vegetarian restaurant": [DietaryPreference.VEGETARIAN],
    "Vegetarian cafe and deli": [DietaryPreference.VEGETARIAN, EstablishmentType.CAFE],
    "Organic restaurant": [DietaryPreference.VEGETARIAN],
    "Raw food restaurant": [DietaryPreference.VEGETARIAN],
    "Health food restaurant": [DietaryPreference.VEGETARIAN]
}