services:
  api:
    build:
      context: ./api
    container_name: python_api_server
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - ./data:/data
      - ./models:/models
    environment:
      - MONGO_URI=mongodb+srv://ayarotbart_db_user:x0fGOfhRThKnkX4S@cluster0.yodtpzx.mongodb.net/?appName=Cluster0
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend_server
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - DOCKER=true
    depends_on:
      - api
    restart: unless-stopped